/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    certifications: Certification;
    categories: Category;
    products: Product;
    insights: Insight;
    'facility-facts': FacilityFact;
    resources: Resource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    'facility-facts': FacilityFactsSelect<false> | FacilityFactsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'ar' | 'fr' | 'ru') | ('en' | 'ar' | 'fr' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ar' | 'fr' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            variant: 'full' | 'compact';
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            heroImage?: (number | null) | Media;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            variant: 'strip' | 'grid';
            sectionTitle?: string | null;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certStrip';
          }
        | {
            sectionTitle?: string | null;
            variant: 'icon' | 'photo';
            items?:
              | {
                  icon?: string | null;
                  photo?: (number | null) | Media;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            sectionTitle?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBand';
          }
        | {
            title: string;
            description?: string | null;
            file?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documentCard';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  videoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaGallery';
          }
        | {
            sectionTitle?: string | null;
            intro?: string | null;
            variant: 'compact' | 'full';
            highlightedCountryCodes?: string[] | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'exportMap';
          }
        | {
            intro?: string | null;
            address: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactBlock';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  logo?: (number | null) | Media;
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustBar';
          }
        | {
            sectionTitle?: string | null;
            steps?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'exportProcess';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  quote: string;
                  name: string;
                  company?: string | null;
                  country?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  /**
   * Optional per-page overrides. Leave blank to fall back to title / a derived summary (buildMetadata's existing default).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  issuingBody: string;
  logo?: (number | null) | Media;
  certificatePdf?: (number | null) | Media;
  validityNotes?: string | null;
  halal?: boolean | null;
  /**
   * Drives the certifications status board (T-106).
   */
  status?: ('registered' | 'in-certification') | null;
  number?: string | null;
  validFrom?: string | null;
  validTo?: string | null;
  /**
   * e.g. "Frozen vegetables, IQF processing".
   */
  scope?: string | null;
  /**
   * For in-certification items — expected completion date, shown on the status board.
   */
  targetDate?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string | null;
  image?: (number | null) | Media;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  category: number | Category;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imageGallery?:
    | {
        image: number | Media;
        role?: ('pack' | 'macro' | 'context') | null;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  packaging?: string | null;
  /**
   * e.g. "Bakery fillings", "Retail frozen aisle" — short use-case tags.
   */
  applications?: string[] | null;
  /**
   * T-103/MASTER_PLAN §7.3: buyer-facing spec sheet, split by category. Each row: parameter, value, optional unit + test method. Leave a category empty to omit it from the product page.
   */
  specs?: {
    physicoChemical?:
      | {
          parameter: string;
          value: string;
          unit?: string | null;
          /**
           * Test method, e.g. "AOAC 925.10".
           */
          method?: string | null;
          id?: string | null;
        }[]
      | null;
    organoleptic?:
      | {
          parameter: string;
          value: string;
          unit?: string | null;
          /**
           * Test method, e.g. "AOAC 925.10".
           */
          method?: string | null;
          id?: string | null;
        }[]
      | null;
    microbiological?:
      | {
          parameter: string;
          value: string;
          unit?: string | null;
          /**
           * Test method, e.g. "AOAC 925.10".
           */
          method?: string | null;
          id?: string | null;
        }[]
      | null;
    contaminants?:
      | {
          parameter: string;
          value: string;
          unit?: string | null;
          /**
           * Test method, e.g. "AOAC 925.10".
           */
          method?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * T-103/MASTER_PLAN §7.3: packaging formats offered for this product.
   */
  packagingOptions?:
    | {
        /**
         * e.g. "IQF pouch", "Aseptic drum".
         */
        format: string;
        /**
         * e.g. "1 kg", "200 L".
         */
        netWeight: string;
        unitsPerCarton?: number | null;
        cartonsPerPallet?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * T-103/MASTER_PLAN §7.3: shown to buyers sizing a shipment.
   */
  containerLoading?: {
    teu20Units?: number | null;
    teu20NetMT?: number | null;
    palletNote?: string | null;
  };
  /**
   * e.g. "24 months from date of manufacture".
   */
  shelfLife?: string | null;
  /**
   * e.g. "-18°C or below".
   */
  storageTemp?: string | null;
  /**
   * e.g. "1 x 20' container".
   */
  moqRange?: string | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Spec sheets, COAs, other per-product documents. Label is localized, file is not.
   */
  downloads?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional per-product overrides. Leave blank to fall back to name / shortDescription (buildMetadata's existing default).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  certifications?: (number | Certification)[] | null;
  displayOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  coverImage: number | Media;
  category?: (number | null) | Category;
  author?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facility-facts".
 */
export interface FacilityFact {
  id: number;
  /**
   * Stable identifier, e.g. "cold-storage-capacity". Not shown to visitors.
   */
  key: string;
  label: string;
  value: string;
  /**
   * Only verified facts should render on the public site (D-01).
   */
  verified?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  type: 'catalog' | 'brochure' | 'spec-sheet' | 'certificate' | 'other';
  file: number | Media;
  product?: (number | null) | Product;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'facility-facts';
        value: number | FacilityFact;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              heroImage?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              heading?: T;
              body?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certStrip?:
          | T
          | {
              variant?: T;
              sectionTitle?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              sectionTitle?: T;
              variant?: T;
              items?:
                | T
                | {
                    icon?: T;
                    photo?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsBand?:
          | T
          | {
              sectionTitle?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        documentCard?:
          | T
          | {
              title?: T;
              description?: T;
              file?: T;
              id?: T;
              blockName?: T;
            };
        mediaGallery?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    videoUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        exportMap?:
          | T
          | {
              sectionTitle?: T;
              intro?: T;
              variant?: T;
              highlightedCountryCodes?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactBlock?:
          | T
          | {
              intro?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
        trustBar?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        exportProcess?:
          | T
          | {
              sectionTitle?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    company?: T;
                    country?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  issuingBody?: T;
  logo?: T;
  certificatePdf?: T;
  validityNotes?: T;
  halal?: T;
  status?: T;
  number?: T;
  validFrom?: T;
  validTo?: T;
  scope?: T;
  targetDate?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  description?: T;
  imageGallery?:
    | T
    | {
        image?: T;
        role?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  packaging?: T;
  applications?: T;
  specs?:
    | T
    | {
        physicoChemical?:
          | T
          | {
              parameter?: T;
              value?: T;
              unit?: T;
              method?: T;
              id?: T;
            };
        organoleptic?:
          | T
          | {
              parameter?: T;
              value?: T;
              unit?: T;
              method?: T;
              id?: T;
            };
        microbiological?:
          | T
          | {
              parameter?: T;
              value?: T;
              unit?: T;
              method?: T;
              id?: T;
            };
        contaminants?:
          | T
          | {
              parameter?: T;
              value?: T;
              unit?: T;
              method?: T;
              id?: T;
            };
      };
  packagingOptions?:
    | T
    | {
        format?: T;
        netWeight?: T;
        unitsPerCarton?: T;
        cartonsPerPallet?: T;
        id?: T;
      };
  containerLoading?:
    | T
    | {
        teu20Units?: T;
        teu20NetMT?: T;
        palletNote?: T;
      };
  shelfLife?: T;
  storageTemp?: T;
  moqRange?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  downloads?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  certifications?: T;
  displayOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  body?: T;
  publishedDate?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facility-facts_select".
 */
export interface FacilityFactsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  verified?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  file?: T;
  product?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Company/brand name shown in the header, footer, and copyright across the whole site. Also used as the logo's alt text.
   */
  siteName: string;
  /**
   * Optional brand logo. When set, it replaces the text wordmark in the header, footer, and mobile menu. Leave empty to show the site name as text. Recommended: transparent PNG/SVG, ~40px tall.
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon. Leave empty to use the default VNP monogram. Recommended: square (e.g. 512x512) transparent PNG or SVG — any other aspect ratio gets letterboxed into a square automatically.
   */
  favicon?: (number | null) | Media;
  /**
   * Hero background photo for the /products catalog page. That page isn't a CMS Page (it's the product catalog listing), so its hero image lives here instead of on a Pages layout block.
   */
  productsHeroImage?: (number | null) | Media;
  /**
   * Hero background photo for the /insights listing page. Same reason as productsHeroImage: not a CMS Page.
   */
  insightsHeroImage?: (number | null) | Media;
  /**
   * Single source for contact details used site-wide — header/hero CTAs, product pages, and the Contact page all read from here.
   */
  contact: {
    /**
     * Inquiry email (mailto: links across the site).
     */
    email: string;
    /**
     * Phone number (tel: link).
     */
    phone: string;
    /**
     * WhatsApp number in E.164 digits, no '+' (e.g. 919876543210). Powers every 'Chat on WhatsApp' link.
     */
    whatsapp: string;
  };
  /**
   * Legal/registered office address. Used for the Organization structured-data (JSON-LD) markup (D-09) and the footer's Registered Office line.
   */
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Manufacturing facility address, shown separately from the registered office (e.g. on the Manufacturing/Company pages and footer).
   */
  factoryAddress?: {
    /**
     * e.g. the facility or partner name.
     */
    facilityName?: string | null;
    street?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * T-102/COMPONENT_LIBRARY C-03: shown as a small one-line strip in the footer, e.g. "CIN U12345MH2026PTC000000 · GST 27ABCDE1234F1Z5". Leave any field blank until the real number is issued — the footer only shows the ones that are actually filled in, never a placeholder dash.
   */
  legalIdentity?: {
    cin?: string | null;
    gst?: string | null;
    iec?: string | null;
    fssai?: string | null;
  };
  /**
   * T-103/MASTER_PLAN §7.3: shown near RFQ/contact CTAs, e.g. "We respond within 24 hours." Leave blank to omit.
   */
  sla?: {
    responseTime?: string | null;
  };
  /**
   * Official profile URLs (LinkedIn, etc.) included in the Organization structured-data markup.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  productsHeroImage?: T;
  insightsHeroImage?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  factoryAddress?:
    | T
    | {
        facilityName?: T;
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  legalIdentity?:
    | T
    | {
        cin?: T;
        gst?: T;
        iec?: T;
        fssai?: T;
      };
  sla?:
    | T
    | {
        responseTime?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}