// One-off content update (not a schema migration) — user-reported: "logo
// looks small, increased size multiple times, no visible change." Root
// cause found: the uploaded logo file is a 1536x1024 canvas where the
// actual visible mark (leaf icon + "VNP GLOBAL" wordmark) only occupies a
// 1083x299 region (~29% of the canvas height) — sharp's .trim() confirmed
// this precisely. Increasing the CSS box height just scaled the WHOLE
// canvas including ~70% of empty transparent padding proportionally; the
// visible-mark-to-box ratio never improved no matter how large the box got.
// scripts/seed-assets/vnp-logo-cropped.png is that region re-exported with
// ~5-15% breathing-room padding (generated once via sharp .extract(), see
// commit — not regenerated by this script, committed as a real asset like
// scripts/seed-assets/*.svg already are for seed-products.ts).
// Idempotent: skips if SiteSettings.logo's filename already matches.
import nextEnv from "@next/env";

nextEnv.loadEnvConfig(process.cwd());

const { getPayload } = await import("payload");
const { default: config } = await import("../src/payload.config");

const payload = await getPayload({ config });

const settings = await payload.findGlobal({ slug: "site-settings", overrideAccess: true });
const currentLogo = settings?.logo;
const currentFilename =
  currentLogo && typeof currentLogo === "object" && "filename" in currentLogo
    ? currentLogo.filename
    : null;

if (typeof currentFilename === "string" && currentFilename.includes("vnp-logo-cropped")) {
  console.log("Logo already replaced with the cropped version — skipping.");
  await payload.destroy();
  process.exit(0);
}

const newLogo = await payload.create({
  collection: "media",
  data: { alt: "VNP Global" },
  filePath: "scripts/seed-assets/vnp-logo-cropped.png",
  overrideAccess: true,
});

await payload.updateGlobal({
  slug: "site-settings",
  data: { logo: newLogo.id },
  overrideAccess: true,
  context: { disableRevalidate: true },
});

console.log(`Logo replaced. New Media id: ${newLogo.id}, filename: ${newLogo.filename}`);

await payload.destroy();
process.exit(0);
